"""Initial database setup

Revision ID: 5b0b307f800c
Revises: 
Create Date: 2025-03-27 11:21:14.019297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0b307f800c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('resume_file_path', sa.String(length=255), nullable=True),
    sa.Column('resume_filename', sa.String(length=255), nullable=True),
    sa.Column('resume_mime_type', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('projects', sa.Text(), nullable=True),
    sa.Column('professional_summary', sa.Text(), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('authorization_status', sa.String(length=100), nullable=True),
    sa.Column('desired_job_titles', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('portfolio_links', sa.Text(), nullable=True),
    sa.Column('desired_salary_range', sa.String(length=100), nullable=True),
    sa.Column('work_mode_preference', sa.String(length=50), nullable=True),
    sa.Column('available_start_date', sa.Date(), nullable=True),
    sa.Column('preferred_company_type', sa.String(length=100), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('biggest_achievement', sa.Text(), nullable=True),
    sa.Column('work_style', sa.Text(), nullable=True),
    sa.Column('industry_attraction', sa.Text(), nullable=True),
    sa.Column('applicant_values', sa.Text(), nullable=True),
    sa.Column('race_ethnicity', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('military_status', sa.String(length=100), nullable=True),
    sa.Column('military_branch', sa.String(length=100), nullable=True),
    sa.Column('military_discharge_date', sa.Date(), nullable=True),
    sa.Column('disability_status', sa.String(length=100), nullable=True),
    sa.Column('needs_sponsorship', sa.Boolean(), nullable=True),
    sa.Column('visa_status', sa.String(length=100), nullable=True),
    sa.Column('veteran_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.Column('recommended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_recommendations')
    op.drop_table('applications')
    op.drop_table('users')
    # ### end Alembic commands ###
