"""Initial migration

Revision ID: 8bd7bccf2ca3
Revises: 
Create Date: 2025-03-18 20:29:38.705881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd7bccf2ca3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_ethnicity', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('graduation_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('military_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('military_branch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('military_discharge_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('disability_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('needs_sponsorship', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('visa_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('veteran_status', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('veteran_status')
        batch_op.drop_column('visa_status')
        batch_op.drop_column('needs_sponsorship')
        batch_op.drop_column('disability_status')
        batch_op.drop_column('military_discharge_date')
        batch_op.drop_column('military_branch')
        batch_op.drop_column('military_status')
        batch_op.drop_column('graduation_date')
        batch_op.drop_column('gender')
        batch_op.drop_column('race_ethnicity')

    # ### end Alembic commands ###
